spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/journy}
    username: ${SPRING_DATASOURCE_USERNAME:journy}
    password: ${SPRING_DATASOURCE_PASSWORD:journy}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
